# Generated by Django 5.0.4 on 2024-05-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='orderTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=200)),
                ('productCount', models.IntegerField(default=1)),
                ('testInt', models.IntegerField(default=5)),
            ],
        ),
    ]
