# Generated by Django 5.0.4 on 2024-05-10 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertable',
            name='testInt',
        ),
    ]
