# Generated by Django 4.1.13 on 2024-05-11 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_ordertable_testint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertable',
            name='testInt',
        ),
    ]
