# Generated by Django 5.0.4 on 2024-05-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinput',
            name='counter',
            field=models.IntegerField(default=5),
        ),
    ]
