# Generated by Django 4.1.13 on 2024-05-11 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_userinput_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinput',
            name='counter',
        ),
    ]
